# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' slr_rsquared
#'
#' @name slr_rsquared
#'
#' @description Gets the coefficients of the simple linear regression model
#'
#' @param x Predictor
#' @param y Response
#'
#' @return the r squared of linear regression model for predictor x and response y
#'
#' @examples
#' slr_rsquared(c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14),c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69))
#'
#' @export
#'
NULL

slr_rsquared <- function(x, y) {
    .Call(`_slrmodel_slr_rsquared`, x, y)
}

