# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_slrmodel_rcpp_hello`)
}

slr_rsquared <- function(x, y) {
    .Call(`_slrmodel_slr_rsquared`, x, y)
}

